import Link from "next/link";
import { Zap, FileText } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | RankVillage AI",
  description: "Read the Terms of Service for RankVillage AI platform.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using RankVillage AI ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.

These Terms apply to all users of the Service, including businesses, individuals, and organizations that access or use the Service.`,
  },
  {
    title: "2. Description of Service",
    content: `RankVillage AI provides an AI-powered Local SEO and Business Growth platform that includes:

• AI Review Reply Generator
• Google Business Profile Optimizer
• Local SEO Analyzer
• Schema Generator
• AI Content Generator
• Keyword Ranking Tracker
• Competitor Analysis
• Business Listing Management

The Service is provided on a subscription basis with plans as described on our Pricing page.`,
  },
  {
    title: "3. Account Registration",
    content: `To use the Service, you must create an account. You agree to:

• Provide accurate, current, and complete information during registration
• Maintain and promptly update your account information
• Keep your password secure and confidential
• Notify us immediately of any unauthorized use of your account
• Be responsible for all activities that occur under your account

You must be at least 18 years old to create an account. By creating an account, you represent that you are 18 or older.`,
  },
  {
    title: "4. Subscription and Payment",
    content: `4.1 Subscription Plans: We offer Starter (₹999/mo), Pro (₹2,499/mo), and Business (₹5,999/mo) plans. Annual plans are available at a 20% discount.

4.2 Free Trial: New accounts receive a 14-day free trial. No credit card is required to start the trial.

4.3 Billing: Subscriptions are billed monthly or annually in advance. Payments are processed through Razorpay.

4.4 Cancellation: You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial periods.

4.5 Price Changes: We reserve the right to change subscription prices with 30 days' notice.`,
  },
  {
    title: "5. Acceptable Use",
    content: `You agree not to use the Service to:

• Violate any applicable laws or regulations
• Infringe on intellectual property rights of others
• Transmit spam, malware, or harmful content
• Attempt to gain unauthorized access to our systems
• Use the Service for any fraudulent or deceptive purpose
• Resell or redistribute the Service without authorization
• Scrape or harvest data from our platform
• Interfere with the proper functioning of the Service`,
  },
  {
    title: "6. Google API Usage",
    content: `Our Service uses Google APIs to access and manage your Google Business Profile. By using our Service, you authorize us to access your Google account data as described in our Privacy Policy.

Your use of Google services through our platform is also subject to Google's Terms of Service and Privacy Policy. We are not responsible for changes to Google's APIs or policies that may affect our Service.`,
  },
  {
    title: "7. Intellectual Property",
    content: `7.1 Our IP: The Service, including all software, algorithms, designs, and content, is owned by RankVillage AI and protected by intellectual property laws.

7.2 Your Content: You retain ownership of content you create using our Service (reviews, posts, descriptions). By using our Service, you grant us a limited license to process your content to provide the Service.

7.3 AI-Generated Content: Content generated by our AI tools is provided for your use. You are responsible for reviewing and ensuring the accuracy of AI-generated content before publishing.`,
  },
  {
    title: "8. Disclaimer of Warranties",
    content: `THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT:

• The Service will be uninterrupted or error-free
• Results from using the Service will meet your expectations
• Specific Google rankings or business outcomes will be achieved
• AI-generated content will be accurate or suitable for all purposes

SEO results depend on many factors outside our control, including Google's algorithms, competition, and market conditions.`,
  },
  {
    title: "9. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, RANKVILLAGE AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES.

Our total liability to you for any claims arising from these Terms or the Service shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: "10. Termination",
    content: `We may suspend or terminate your account if you violate these Terms. You may terminate your account at any time by contacting support@rankvillage.ai.

Upon termination, your right to use the Service ceases immediately. We may retain your data for up to 90 days after termination before permanent deletion.`,
  },
  {
    title: "11. Governing Law",
    content: `These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka, India.

For disputes under ₹50,000, we encourage resolution through our support team before pursuing legal action.`,
  },
  {
    title: "12. Contact",
    content: `For questions about these Terms, contact us at:

Email: legal@rankvillage.ai
Address: RankVillage AI, Bangalore, Karnataka, India - 560001`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080812]">
      <div className="absolute inset-0 grid-bg opacity-10 pointer-events-none" />

      <nav className="border-b border-white/5 bg-[#080812]/90 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-base"><span className="gradient-text">RankVillage</span><span className="text-white/40 text-sm font-normal ml-1">AI</span></span>
          </Link>
          <Link href="/" className="text-sm text-white/50 hover:text-white transition-colors">← Back to Home</Link>
        </div>
      </nav>

      <div className="relative max-w-4xl mx-auto px-4 sm:px-6 py-16">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-blue-500/20 text-sm text-blue-300 mb-6">
            <FileText className="w-3.5 h-3.5" /> Terms of Service
          </div>
          <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
          <p className="text-white/50">Last updated: June 1, 2025</p>
          <p className="text-white/50 mt-3 leading-relaxed">
            Please read these Terms of Service carefully before using RankVillage AI. These terms govern your use of our platform and services.
          </p>
        </div>

        <div className="space-y-8">
          {sections.map((section) => (
            <div key={section.title} className="glass-card rounded-2xl p-6 border border-white/5">
              <h2 className="text-lg font-semibold text-white mb-4">{section.title}</h2>
              <div className="text-white/50 text-sm leading-relaxed whitespace-pre-line">{section.content}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="border-t border-white/5 py-8 text-center">
        <p className="text-white/30 text-sm">
          © {new Date().getFullYear()} RankVillage AI · <Link href="/terms" className="hover:text-white/50 transition-colors">Terms of Service</Link> · <Link href="/privacy" className="hover:text-white/50 transition-colors">Privacy Policy</Link>
        </p>
      </div>
    </div>
  );
}
